# Generated by Django 5.2.1 on 2025-05-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireDectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('frame', models.ImageField(blank=True, null=True, upload_to='fdetections/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.camera')),
            ],
        ),
    ]
