# Generated by Django 5.2.1 on 2025-05-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_ip',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='FireDetectedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('confidence', models.FloatField()),
                ('detected_frame', models.ImageField(blank=True, null=True, upload_to='fdetections/')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.camera')),
            ],
        ),
        migrations.DeleteModel(
            name='FireDectionEvent',
        ),
    ]
