# Generated by Django 5.2.1 on 2025-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_camera_camera_ip_firedetectedalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
